//! 模型目录：103 个 NIM 模型（从 Go 源码静态提取，2026-08-06）

use std::collections::HashMap;
use std::sync::LazyLock;
use std::sync::atomic::{AtomicBool, Ordering};

#[derive(Debug, Clone)]
pub struct ModelInfo {
    pub model_id: String,
    pub display_name: String,
    pub cn_name: String,
    pub context_length: i64,
    pub max_output_tokens: i64,
    pub supports_streaming: bool,
    pub supports_tools: bool,
    pub supports_images: bool,
    pub model_family: String,
    pub tags: Vec<String>,
    pub extra_aliases: Vec<String>,
}

pub static NIMMODEL_CATALOG: LazyLock<HashMap<String, ModelInfo>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("z-ai/glm-5.2".to_string(), ModelInfo {
        model_id: "z-ai/glm-5.2".to_string(),
        display_name: "GLM-5.2".to_string(),
        cn_name: "".to_string(),
        context_length: 202752,
        max_output_tokens: 16000,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "glm".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("deepseek-ai/deepseek-v4-flash".to_string(), ModelInfo {
        model_id: "deepseek-ai/deepseek-v4-flash".to_string(),
        display_name: "DeepSeek-V4-Flash".to_string(),
        cn_name: "".to_string(),
        context_length: 0,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "deepseek".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    // DeepSeek V4 Flash 正式版（2026-07-31 上线，NVIDIA NIM 新 id；官方 1M 上下文 / 384K 输出）
    m.insert("deepseek-ai/deepseek-v4-flash-0731".to_string(), ModelInfo {
        model_id: "deepseek-ai/deepseek-v4-flash-0731".to_string(),
        display_name: "DeepSeek-V4-Flash-0731".to_string(),
        cn_name: "DeepSeek V4 Flash 正式版".to_string(),
        context_length: 1000000,
        max_output_tokens: 384000,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "deepseek-ai".to_string(),
        tags: vec![],
        extra_aliases: vec!["deepseek-ai/deepseek-v4-flash".to_string()],
    });
    m.insert("deepseek-ai/deepseek-v4-pro".to_string(), ModelInfo {
        model_id: "deepseek-ai/deepseek-v4-pro".to_string(),
        display_name: "DeepSeek-V4-Pro".to_string(),
        cn_name: "".to_string(),
        context_length: 262144,
        max_output_tokens: 32768,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "deepseek".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("minimaxai/minimax-m3".to_string(), ModelInfo {
        model_id: "minimaxai/minimax-m3".to_string(),
        display_name: "MiniMax-M3".to_string(),
        cn_name: "".to_string(),
        context_length: 262144,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "minimax".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("stepfun-ai/step-3.7-flash".to_string(), ModelInfo {
        model_id: "stepfun-ai/step-3.7-flash".to_string(),
        display_name: "Step-3.7-Flash".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "step".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("deepseek-ai/deepseek-coder-6.7b-instruct".to_string(), ModelInfo {
        model_id: "deepseek-ai/deepseek-coder-6.7b-instruct".to_string(),
        display_name: "DeepSeek-Coder-6.7B".to_string(),
        cn_name: "".to_string(),
        context_length: 32768,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "deepseek".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("google/gemma-3-12b-it".to_string(), ModelInfo {
        model_id: "google/gemma-3-12b-it".to_string(),
        display_name: "Gemma-3-12B".to_string(),
        cn_name: "".to_string(),
        context_length: 32768,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "gemma".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("google/gemma-3-4b-it".to_string(), ModelInfo {
        model_id: "google/gemma-3-4b-it".to_string(),
        display_name: "Gemma-3-4B".to_string(),
        cn_name: "".to_string(),
        context_length: 32768,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "gemma".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("moonshotai/kimi-k2.6".to_string(), ModelInfo {
        model_id: "moonshotai/kimi-k2.6".to_string(),
        display_name: "Kimi-K2.6".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "kimi".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nv-mistralai/mistral-nemo-12b-instruct".to_string(), ModelInfo {
        model_id: "nv-mistralai/mistral-nemo-12b-instruct".to_string(),
        display_name: "Mistral-NeMo-12B".to_string(),
        cn_name: "".to_string(),
        context_length: 128000,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "mistral".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("openai/gpt-oss-120b".to_string(), ModelInfo {
        model_id: "openai/gpt-oss-120b".to_string(),
        display_name: "GPT-OSS-120B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "gpt".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("openai/gpt-oss-20b".to_string(), ModelInfo {
        model_id: "openai/gpt-oss-20b".to_string(),
        display_name: "GPT-OSS-20B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "gpt".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("meta/llama-3.1-70b-instruct".to_string(), ModelInfo {
        model_id: "meta/llama-3.1-70b-instruct".to_string(),
        display_name: "Llama-3.1-70B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "llama".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("meta/llama-3.1-8b-instruct".to_string(), ModelInfo {
        model_id: "meta/llama-3.1-8b-instruct".to_string(),
        display_name: "Llama-3.1-8B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "llama".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("meta/llama-3.2-90b-vision-instruct".to_string(), ModelInfo {
        model_id: "meta/llama-3.2-90b-vision-instruct".to_string(),
        display_name: "Llama-3.2-90B-Vision".to_string(),
        cn_name: "".to_string(),
        context_length: 32768,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "llama".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("meta/llama-3.2-11b-vision-instruct".to_string(), ModelInfo {
        model_id: "meta/llama-3.2-11b-vision-instruct".to_string(),
        display_name: "Llama-3.2-11B-Vision".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "llama".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("meta/llama-3.2-3b-instruct".to_string(), ModelInfo {
        model_id: "meta/llama-3.2-3b-instruct".to_string(),
        display_name: "Llama-3.2-3B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "llama".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("meta/llama-3.2-1b-instruct".to_string(), ModelInfo {
        model_id: "meta/llama-3.2-1b-instruct".to_string(),
        display_name: "Llama-3.2-1B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "llama".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("meta/llama-3.3-70b-instruct".to_string(), ModelInfo {
        model_id: "meta/llama-3.3-70b-instruct".to_string(),
        display_name: "Llama-3.3-70B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "llama".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("meta/llama-guard-4-12b".to_string(), ModelInfo {
        model_id: "meta/llama-guard-4-12b".to_string(),
        display_name: "Llama-Guard-4-12B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: false,
        supports_images: true,
        model_family: "llama-guard".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    // Meta Muse Glimmer 30B（2026-08-10 发布；官方 131K 上下文，多模态 text+image，函数调用/推理）
    m.insert("meta/muse-glimmer-30b".to_string(), ModelInfo {
        model_id: "meta/muse-glimmer-30b".to_string(),
        display_name: "Muse-Glimmer-30B".to_string(),
        cn_name: "Muse Glimmer 30B".to_string(),
        context_length: 131072,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "meta".to_string(),
        tags: vec!["vision".to_string()],
        extra_aliases: vec![],
    });
    m.insert("google/gemma-4-31b-it".to_string(), ModelInfo {
        model_id: "google/gemma-4-31b-it".to_string(),
        display_name: "Gemma-4-31B".to_string(),
        cn_name: "".to_string(),
        context_length: 262144,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "gemma".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("google/diffusiongemma-26b-a4b-it".to_string(), ModelInfo {
        model_id: "google/diffusiongemma-26b-a4b-it".to_string(),
        display_name: "DiffusionGemma-26B".to_string(),
        cn_name: "".to_string(),
        context_length: 16384,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "diffusiongemma".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("mistralai/mistral-medium-3.5-128b".to_string(), ModelInfo {
        model_id: "mistralai/mistral-medium-3.5-128b".to_string(),
        display_name: "Mistral-Medium-3.5-128B".to_string(),
        cn_name: "".to_string(),
        context_length: 262144,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "mistral".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("mistralai/mistral-nemotron".to_string(), ModelInfo {
        model_id: "mistralai/mistral-nemotron".to_string(),
        display_name: "Mistral-Nemotron".to_string(),
        cn_name: "".to_string(),
        context_length: 177152,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "mistral".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nemotron-3-ultra-550b-a55b".to_string(), ModelInfo {
        model_id: "nvidia/nemotron-3-ultra-550b-a55b".to_string(),
        display_name: "Nemotron-3-Ultra-550B".to_string(),
        cn_name: "".to_string(),
        context_length: 524288,
        max_output_tokens: 32768,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nemotron-3-super-120b-a12b".to_string(), ModelInfo {
        model_id: "nvidia/nemotron-3-super-120b-a12b".to_string(),
        display_name: "Nemotron-3-Super-120B".to_string(),
        cn_name: "".to_string(),
        context_length: 1048576,
        max_output_tokens: 32768,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nemotron-3-nano-30b-a3b".to_string(), ModelInfo {
        model_id: "nvidia/nemotron-3-nano-30b-a3b".to_string(),
        display_name: "Nemotron-3-Nano-30B".to_string(),
        cn_name: "".to_string(),
        context_length: 524288,
        max_output_tokens: 32768,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nemotron-3-nano-omni-30b-a3b-reasoning".to_string(), ModelInfo {
        model_id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning".to_string(),
        display_name: "Nemotron-3-Nano-Omni-30B-Reasoning".to_string(),
        cn_name: "".to_string(),
        context_length: 512000,
        max_output_tokens: 20480,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-3.3-nemotron-super-49b-v1.5".to_string(), ModelInfo {
        model_id: "nvidia/llama-3.3-nemotron-super-49b-v1.5".to_string(),
        display_name: "Llama-3.3-Nemotron-Super-49B-v1.5".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-3.3-nemotron-super-49b-v1".to_string(), ModelInfo {
        model_id: "nvidia/llama-3.3-nemotron-super-49b-v1".to_string(),
        display_name: "Llama-3.3-Nemotron-Super-49B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-3.1-nemotron-nano-vl-8b-v1".to_string(), ModelInfo {
        model_id: "nvidia/llama-3.1-nemotron-nano-vl-8b-v1".to_string(),
        display_name: "Llama-3.1-Nemotron-Nano-VL-8B".to_string(),
        cn_name: "".to_string(),
        context_length: 16384,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nemotron-nano-12b-v2-vl".to_string(), ModelInfo {
        model_id: "nvidia/nemotron-nano-12b-v2-vl".to_string(),
        display_name: "Nemotron-Nano-12B-v2-VL".to_string(),
        cn_name: "".to_string(),
        context_length: 65536,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: false,
        supports_images: true,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nvidia-nemotron-nano-9b-v2".to_string(), ModelInfo {
        model_id: "nvidia/nvidia-nemotron-nano-9b-v2".to_string(),
        display_name: "Nemotron-Nano-9B-v2".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nemotron-mini-4b-instruct".to_string(), ModelInfo {
        model_id: "nvidia/nemotron-mini-4b-instruct".to_string(),
        display_name: "Nemotron-Mini-4B".to_string(),
        cn_name: "".to_string(),
        context_length: 4096,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-3.1-nemotron-51b-instruct".to_string(), ModelInfo {
        model_id: "nvidia/llama-3.1-nemotron-51b-instruct".to_string(),
        display_name: "Llama-3.1-Nemotron-51B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-3.1-nemotron-70b-instruct".to_string(), ModelInfo {
        model_id: "nvidia/llama-3.1-nemotron-70b-instruct".to_string(),
        display_name: "Llama-3.1-Nemotron-70B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-3.1-nemotron-ultra-253b-v1".to_string(), ModelInfo {
        model_id: "nvidia/llama-3.1-nemotron-ultra-253b-v1".to_string(),
        display_name: "Nemotron-Ultra-253B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-3.1-nemotron-nano-8b-v1".to_string(), ModelInfo {
        model_id: "nvidia/llama-3.1-nemotron-nano-8b-v1".to_string(),
        display_name: "Nemotron-Nano-8B-v1".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nemotron-nano-3-30b-a3b".to_string(), ModelInfo {
        model_id: "nvidia/nemotron-nano-3-30b-a3b".to_string(),
        display_name: "Nemotron-Nano-3-30B".to_string(),
        cn_name: "".to_string(),
        context_length: 259072,
        max_output_tokens: 32768,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-3.1-nemoguard-8b-content-safety".to_string(), ModelInfo {
        model_id: "nvidia/llama-3.1-nemoguard-8b-content-safety".to_string(),
        display_name: "Llama-3.1-NemoGuard-8B-Content-Safety".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "nemoguard".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-3.1-nemoguard-8b-topic-control".to_string(), ModelInfo {
        model_id: "nvidia/llama-3.1-nemoguard-8b-topic-control".to_string(),
        display_name: "Llama-3.1-NemoGuard-8B-Topic-Control".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "nemoguard".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-3.1-nemotron-safety-guard-8b-v3".to_string(), ModelInfo {
        model_id: "nvidia/llama-3.1-nemotron-safety-guard-8b-v3".to_string(),
        display_name: "Llama-3.1-Nemotron-Safety-Guard-8B-v3".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nemotron-3.5-content-safety".to_string(), ModelInfo {
        model_id: "nvidia/nemotron-3.5-content-safety".to_string(),
        display_name: "Nemotron-3.5-Content-Safety".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: false,
        supports_images: true,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/riva-translate-4b-instruct-v1.1".to_string(), ModelInfo {
        model_id: "nvidia/riva-translate-4b-instruct-v1.1".to_string(),
        display_name: "Riva-Translate-4B-v1.1".to_string(),
        cn_name: "".to_string(),
        context_length: 4096,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "riva".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/riva-translate-4b-instruct".to_string(), ModelInfo {
        model_id: "nvidia/riva-translate-4b-instruct".to_string(),
        display_name: "Riva-Translate-4B".to_string(),
        cn_name: "".to_string(),
        context_length: 2048,
        max_output_tokens: 512,
        supports_streaming: false,
        supports_tools: false,
        supports_images: false,
        model_family: "riva".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/riva-translate-4b-instruct-v2".to_string(), ModelInfo {
        model_id: "nvidia/riva-translate-4b-instruct-v2".to_string(),
        display_name: "Riva-Translate-4B-v2".to_string(),
        cn_name: "".to_string(),
        context_length: 4096,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "riva".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/vila".to_string(), ModelInfo {
        model_id: "nvidia/vila".to_string(),
        display_name: "VILA".to_string(),
        cn_name: "".to_string(),
        context_length: 8192,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: false,
        supports_images: true,
        model_family: "nvidia".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nemotron-parse".to_string(), ModelInfo {
        model_id: "nvidia/nemotron-parse".to_string(),
        display_name: "Nemotron-Parse".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: false,
        supports_images: true,
        model_family: "nvidia".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("poolside/laguna-xs-2.1".to_string(), ModelInfo {
        model_id: "poolside/laguna-xs-2.1".to_string(),
        display_name: "Laguna-XS-2.1".to_string(),
        cn_name: "".to_string(),
        context_length: 32768,
        max_output_tokens: 8192,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "laguna".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("thinkingmachines/inkling".to_string(), ModelInfo {
        model_id: "thinkingmachines/inkling".to_string(),
        display_name: "Inkling".to_string(),
        cn_name: "".to_string(),
        context_length: 65536,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "inkling".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("01-ai/yi-large".to_string(), ModelInfo {
        model_id: "01-ai/yi-large".to_string(),
        display_name: "Yi-Large".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "01".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("adept/fuyu-8b".to_string(), ModelInfo {
        model_id: "adept/fuyu-8b".to_string(),
        display_name: "Fuyu-8B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "adept".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("ai21labs/jamba-1.5-large-instruct".to_string(), ModelInfo {
        model_id: "ai21labs/jamba-1.5-large-instruct".to_string(),
        display_name: "Jamba-1.5-Large-Instruct".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "ai21labs".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("aisingapore/sea-lion-7b-instruct".to_string(), ModelInfo {
        model_id: "aisingapore/sea-lion-7b-instruct".to_string(),
        display_name: "Sea-Lion-7B-Instruct".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "aisingapore".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("baai/bge-m3".to_string(), ModelInfo {
        model_id: "baai/bge-m3".to_string(),
        display_name: "Bge-M3".to_string(),
        cn_name: "".to_string(),
        context_length: 4096,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "baai".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("bigcode/starcoder2-15b".to_string(), ModelInfo {
        model_id: "bigcode/starcoder2-15b".to_string(),
        display_name: "Starcoder2-15B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "bigcode".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("databricks/dbrx-instruct".to_string(), ModelInfo {
        model_id: "databricks/dbrx-instruct".to_string(),
        display_name: "Dbrx-Instruct".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "databricks".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("google/codegemma-1.1-7b".to_string(), ModelInfo {
        model_id: "google/codegemma-1.1-7b".to_string(),
        display_name: "Codegemma-1.1-7B".to_string(),
        cn_name: "".to_string(),
        context_length: 8192,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "gemma".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("google/codegemma-7b".to_string(), ModelInfo {
        model_id: "google/codegemma-7b".to_string(),
        display_name: "Codegemma-7B".to_string(),
        cn_name: "".to_string(),
        context_length: 8192,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: false,
        supports_images: false,
        model_family: "gemma".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("google/deplot".to_string(), ModelInfo {
        model_id: "google/deplot".to_string(),
        display_name: "Deplot".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "gemma".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("google/gemma-2b".to_string(), ModelInfo {
        model_id: "google/gemma-2b".to_string(),
        display_name: "Gemma-2B".to_string(),
        cn_name: "".to_string(),
        context_length: 8192,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "gemma".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("google/recurrentgemma-2b".to_string(), ModelInfo {
        model_id: "google/recurrentgemma-2b".to_string(),
        display_name: "Recurrentgemma-2B".to_string(),
        cn_name: "".to_string(),
        context_length: 8192,
        max_output_tokens: 4096,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "gemma".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("ibm/granite-3.0-3b-a800m-instruct".to_string(), ModelInfo {
        model_id: "ibm/granite-3.0-3b-a800m-instruct".to_string(),
        display_name: "Granite-3.0-3B-A800M-Instruct".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "granite".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("ibm/granite-3.0-8b-instruct".to_string(), ModelInfo {
        model_id: "ibm/granite-3.0-8b-instruct".to_string(),
        display_name: "Granite-3.0-8B-Instruct".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "granite".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("ibm/granite-34b-code-instruct".to_string(), ModelInfo {
        model_id: "ibm/granite-34b-code-instruct".to_string(),
        display_name: "Granite-34B-Code-Instruct".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "granite".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("ibm/granite-8b-code-instruct".to_string(), ModelInfo {
        model_id: "ibm/granite-8b-code-instruct".to_string(),
        display_name: "Granite-8B-Code-Instruct".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "granite".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("meta/codellama-70b".to_string(), ModelInfo {
        model_id: "meta/codellama-70b".to_string(),
        display_name: "Codellama-70B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "llama".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("meta/llama2-70b".to_string(), ModelInfo {
        model_id: "meta/llama2-70b".to_string(),
        display_name: "Llama2-70B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "llama".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("microsoft/kosmos-2".to_string(), ModelInfo {
        model_id: "microsoft/kosmos-2".to_string(),
        display_name: "Kosmos-2".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "phi".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("microsoft/phi-3-vision-128k-instruct".to_string(), ModelInfo {
        model_id: "microsoft/phi-3-vision-128k-instruct".to_string(),
        display_name: "Phi-3-Vision-128K-Instruct".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "phi".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("microsoft/phi-3.5-moe-instruct".to_string(), ModelInfo {
        model_id: "microsoft/phi-3.5-moe-instruct".to_string(),
        display_name: "Phi-3.5-Moe-Instruct".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "phi".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("mistralai/codestral-22b-instruct-v0.1".to_string(), ModelInfo {
        model_id: "mistralai/codestral-22b-instruct-v0.1".to_string(),
        display_name: "Codestral-22B-Instruct-V0.1".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "mistral".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("mistralai/mistral-7b-instruct-v0.3".to_string(), ModelInfo {
        model_id: "mistralai/mistral-7b-instruct-v0.3".to_string(),
        display_name: "Mistral-7B-Instruct-V0.3".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "mistral".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("mistralai/mistral-large".to_string(), ModelInfo {
        model_id: "mistralai/mistral-large".to_string(),
        display_name: "Mistral-Large".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "mistral".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("mistralai/mistral-large-2-instruct".to_string(), ModelInfo {
        model_id: "mistralai/mistral-large-2-instruct".to_string(),
        display_name: "Mistral-Large-2-Instruct".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "mistral".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("mistralai/mixtral-8x22b-v0.1".to_string(), ModelInfo {
        model_id: "mistralai/mixtral-8x22b-v0.1".to_string(),
        display_name: "Mixtral-8X22B-V0.1".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "mistral".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/ai-synthetic-video-detector".to_string(), ModelInfo {
        model_id: "nvidia/ai-synthetic-video-detector".to_string(),
        display_name: "Ai-Synthetic-Video-Detector".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/cosmos-reason2-8b".to_string(), ModelInfo {
        model_id: "nvidia/cosmos-reason2-8b".to_string(),
        display_name: "Cosmos-Reason2-8B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/embed-qa-4".to_string(), ModelInfo {
        model_id: "nvidia/embed-qa-4".to_string(),
        display_name: "Embed-Qa-4".to_string(),
        cn_name: "".to_string(),
        context_length: 4096,
        max_output_tokens: 4096,
        supports_streaming: false,
        supports_tools: false,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/ising-calibration-1.5-31b".to_string(), ModelInfo {
        model_id: "nvidia/ising-calibration-1.5-31b".to_string(),
        display_name: "Ising-Calibration-1.5-31B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1".to_string(), ModelInfo {
        model_id: "nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1".to_string(),
        display_name: "Llama-3.2-Nemoretriever-1B-Vlm-Embed-V1".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: false,
        supports_tools: false,
        supports_images: true,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-3.2-nv-embedqa-1b-v1".to_string(), ModelInfo {
        model_id: "nvidia/llama-3.2-nv-embedqa-1b-v1".to_string(),
        display_name: "Llama-3.2-Nv-Embedqa-1B-V1".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: false,
        supports_tools: false,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-nemotron-embed-1b-v2".to_string(), ModelInfo {
        model_id: "nvidia/llama-nemotron-embed-1b-v2".to_string(),
        display_name: "Llama-Nemotron-Embed-1B-V2".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: false,
        supports_tools: false,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama-nemotron-embed-vl-1b-v2".to_string(), ModelInfo {
        model_id: "nvidia/llama-nemotron-embed-vl-1b-v2".to_string(),
        display_name: "Llama-Nemotron-Embed-Vl-1B-V2".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: false,
        supports_tools: false,
        supports_images: true,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/llama3-chatqa-1.5-70b".to_string(), ModelInfo {
        model_id: "nvidia/llama3-chatqa-1.5-70b".to_string(),
        display_name: "Llama3-Chatqa-1.5-70B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/mistral-nemo-minitron-8b-8k-instruct".to_string(), ModelInfo {
        model_id: "nvidia/mistral-nemo-minitron-8b-8k-instruct".to_string(),
        display_name: "Mistral-Nemo-Minitron-8B-8K-Instruct".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nemoretriever-parse".to_string(), ModelInfo {
        model_id: "nvidia/nemoretriever-parse".to_string(),
        display_name: "Nemoretriever-Parse".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: false,
        supports_tools: false,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nemotron-3-embed-1b".to_string(), ModelInfo {
        model_id: "nvidia/nemotron-3-embed-1b".to_string(),
        display_name: "Nemotron-3-Embed-1B".to_string(),
        cn_name: "".to_string(),
        context_length: 1048576,
        max_output_tokens: 16384,
        supports_streaming: false,
        supports_tools: false,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nemotron-4-340b-instruct".to_string(), ModelInfo {
        model_id: "nvidia/nemotron-4-340b-instruct".to_string(),
        display_name: "Nemotron-4-340B-Instruct".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nemotron-4-340b-reward".to_string(), ModelInfo {
        model_id: "nvidia/nemotron-4-340b-reward".to_string(),
        display_name: "Nemotron-4-340B-Reward".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/neva-22b".to_string(), ModelInfo {
        model_id: "nvidia/neva-22b".to_string(),
        display_name: "Neva-22B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nv-embed-v1".to_string(), ModelInfo {
        model_id: "nvidia/nv-embed-v1".to_string(),
        display_name: "Nv-Embed-V1".to_string(),
        cn_name: "".to_string(),
        context_length: 4096,
        max_output_tokens: 4096,
        supports_streaming: false,
        supports_tools: false,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nv-embedcode-7b-v1".to_string(), ModelInfo {
        model_id: "nvidia/nv-embedcode-7b-v1".to_string(),
        display_name: "Nv-Embedcode-7B-V1".to_string(),
        cn_name: "".to_string(),
        context_length: 4096,
        max_output_tokens: 4096,
        supports_streaming: false,
        supports_tools: false,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nv-embedqa-e5-v5".to_string(), ModelInfo {
        model_id: "nvidia/nv-embedqa-e5-v5".to_string(),
        display_name: "Nv-Embedqa-E5-V5".to_string(),
        cn_name: "".to_string(),
        context_length: 4096,
        max_output_tokens: 4096,
        supports_streaming: false,
        supports_tools: false,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nv-embedqa-mistral-7b-v2".to_string(), ModelInfo {
        model_id: "nvidia/nv-embedqa-mistral-7b-v2".to_string(),
        display_name: "Nv-Embedqa-Mistral-7B-V2".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: false,
        supports_tools: false,
        supports_images: false,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("nvidia/nvclip".to_string(), ModelInfo {
        model_id: "nvidia/nvclip".to_string(),
        display_name: "Nvclip".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "nemotron".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("snowflake/arctic-embed-l".to_string(), ModelInfo {
        model_id: "snowflake/arctic-embed-l".to_string(),
        display_name: "Arctic-Embed-L".to_string(),
        cn_name: "".to_string(),
        context_length: 4096,
        max_output_tokens: 4096,
        supports_streaming: false,
        supports_tools: false,
        supports_images: false,
        model_family: "snowflake".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("writer/palmyra-creative-122b".to_string(), ModelInfo {
        model_id: "writer/palmyra-creative-122b".to_string(),
        display_name: "Palmyra-Creative-122B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "writer".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("writer/palmyra-fin-70b-32k".to_string(), ModelInfo {
        model_id: "writer/palmyra-fin-70b-32k".to_string(),
        display_name: "Palmyra-Fin-70B-32K".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "writer".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("writer/palmyra-med-70b".to_string(), ModelInfo {
        model_id: "writer/palmyra-med-70b".to_string(),
        display_name: "Palmyra-Med-70B".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "writer".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("writer/palmyra-med-70b-32k".to_string(), ModelInfo {
        model_id: "writer/palmyra-med-70b-32k".to_string(),
        display_name: "Palmyra-Med-70B-32K".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "writer".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    m.insert("zyphra/zamba2-7b-instruct".to_string(), ModelInfo {
        model_id: "zyphra/zamba2-7b-instruct".to_string(),
        display_name: "Zamba2-7B-Instruct".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "zyphra".to_string(),
        tags: vec![],
        extra_aliases: vec![],
    });
    // ⚠️ 官方自营账号池（Codex/ChatGPT 订阅）已下线，目录条目注释移除；开源版仅保留英伟达 NIM 模型。
    // m.insert("acu/gpt-5.6-luna".to_string(), ModelInfo {
    //     model_id: "acu/gpt-5.6-luna".to_string(),
    //     display_name: "GPT-5.6 Luna".to_string(),
    //     cn_name: "GPT-5.6 Luna（官方自营账号池）".to_string(),
    //     context_length: 400000,
    //     max_output_tokens: 128000,
    //     supports_streaming: true,
    //     supports_tools: true,
    //     supports_images: false,
    //     model_family: "acu".to_string(),
    //     tags: vec!["special".to_string(), "官方自营".to_string()],
    //     extra_aliases: vec!["gpt-5.6-luna".to_string()],
    // });
    // m.insert("acu/gpt-5.6-terra".to_string(), ModelInfo {
    //     model_id: "acu/gpt-5.6-terra".to_string(),
    //     display_name: "GPT-5.6 Terra".to_string(),
    //     cn_name: "GPT-5.6 Terra（官方自营账号池）".to_string(),
    //     context_length: 400000,
    //     max_output_tokens: 128000,
    //     supports_streaming: true,
    //     supports_tools: true,
    //     supports_images: false,
    //     model_family: "acu".to_string(),
    //     tags: vec!["special".to_string(), "官方自营".to_string()],
    //     extra_aliases: vec!["gpt-5.6-terra".to_string()],
    // });
    // m.insert("acu/gpt-5.6-sol".to_string(), ModelInfo {
    //     model_id: "acu/gpt-5.6-sol".to_string(),
    //     display_name: "GPT-5.6 Sol".to_string(),
    //     cn_name: "GPT-5.6 Sol（官方自营账号池）".to_string(),
    //     context_length: 400000,
    //     max_output_tokens: 128000,
    //     supports_streaming: true,
    //     supports_tools: true,
    //     supports_images: false,
    //     model_family: "acu".to_string(),
    //     tags: vec!["special".to_string(), "官方自营".to_string()],
    //     extra_aliases: vec!["gpt-5.6-sol".to_string()],
    // });
    // 官方自营上游模型（acu/ 前缀，走本机 DS2API 独立上游，独立于英伟达 NIM）
    // 上游真实 ID 与平台 ID 相同（全小写），由网关 ACU_MODEL_MAP 改写；is_deprecated 已特判
    m.insert("acu/deepseek-v4-flash".to_string(), ModelInfo {
        model_id: "acu/deepseek-v4-flash".to_string(),
        display_name: "DeepSeek-V4-Flash（官方自营）".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "acu".to_string(),
        tags: vec!["special".to_string(), "官方自营".to_string()],
        extra_aliases: vec![],
    });
    m.insert("acu/deepseek-v4-flash-nothinking".to_string(), ModelInfo {
        model_id: "acu/deepseek-v4-flash-nothinking".to_string(),
        display_name: "DeepSeek-V4-Flash（官方自营·无思考）".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "acu".to_string(),
        tags: vec!["special".to_string(), "官方自营".to_string()],
        extra_aliases: vec![],
    });
    m.insert("acu/deepseek-v4-flash-search".to_string(), ModelInfo {
        model_id: "acu/deepseek-v4-flash-search".to_string(),
        display_name: "DeepSeek-V4-Flash（官方自营·联网）".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "acu".to_string(),
        tags: vec!["special".to_string(), "官方自营".to_string()],
        extra_aliases: vec![],
    });
    m.insert("acu/deepseek-v4-flash-search-nothinking".to_string(), ModelInfo {
        model_id: "acu/deepseek-v4-flash-search-nothinking".to_string(),
        display_name: "DeepSeek-V4-Flash（官方自营·联网·无思考）".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: false,
        model_family: "acu".to_string(),
        tags: vec!["special".to_string(), "官方自营".to_string()],
        extra_aliases: vec![],
    });
    m.insert("acu/deepseek-v4-vision".to_string(), ModelInfo {
        model_id: "acu/deepseek-v4-vision".to_string(),
        display_name: "DeepSeek-V4-Vision（官方自营）".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "acu".to_string(),
        tags: vec!["special".to_string(), "官方自营".to_string()],
        extra_aliases: vec![],
    });
    m.insert("acu/deepseek-v4-vision-nothinking".to_string(), ModelInfo {
        model_id: "acu/deepseek-v4-vision-nothinking".to_string(),
        display_name: "DeepSeek-V4-Vision（官方自营·无思考）".to_string(),
        cn_name: "".to_string(),
        context_length: 131072,
        max_output_tokens: 16384,
        supports_streaming: true,
        supports_tools: true,
        supports_images: true,
        model_family: "acu".to_string(),
        tags: vec!["special".to_string(), "官方自营".to_string()],
        extra_aliases: vec![],
    });
    // 开源版说明：平台专属模型（映射表）已整体裁剪，本仓库仅保留英伟达 NIM 模型与官方自营（acu/）。
    m
});

/// 查询模型信息
pub fn get_model_info(id: &str) -> Option<&ModelInfo> {
    NIMMODEL_CATALOG.get(id)
}

/// 模型数量
pub fn model_count() -> usize {
    NIMMODEL_CATALOG.len()
}

/// 已弃用模型（上游 EOL / 404 下线，2026-08-07 数据驱动更新）
/// 依据：上游实测 —— v4-pro/v4-flash/mistral-medium 返回 410 Gone（EOL 2026-08-07T09:00Z）；
/// 其余 28 个近 24h 全部请求返回 404 且无任何 200 成功（上游已下线）
pub const DEPRECATED_MODELS: [&str; 63] = [
    "deepseek-ai/deepseek-v4-pro",
    "deepseek-ai/deepseek-v4-flash",
    "mistralai/mistral-medium-3.5-128b",
    "deepseek-ai/deepseek-coder-6.7b-instruct",
    "nvidia/llama3-chatqa-1.5-70b",
    "moonshotai/kimi-k2.6",
    "snowflake/arctic-embed-l",
    "01-ai/yi-large",
    "nvidia/nemotron-nano-3-30b-a3b",
    "nvidia/mistral-nemo-minitron-8b-8k-instruct",
    "google/codegemma-1.1-7b",
    "google/gemma-3-12b-it",
    "mistralai/mistral-large",
    "google/deplot",
    "google/gemma-3-4b-it",
    "mistralai/mixtral-8x22b-v0.1",
    "ai21labs/jamba-1.5-large-instruct",
    "mistralai/mistral-large-2-instruct",
    "nvidia/nvclip",
    "bigcode/starcoder2-15b",
    "nv-mistralai/mistral-nemo-12b-instruct",
    "nvidia/nv-embedqa-mistral-7b-v2",
    "nvidia/llama-3.1-nemotron-ultra-253b-v1",
    "writer/palmyra-creative-122b",
    "nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1",
    "ibm/granite-34b-code-instruct",
    "baai/bge-m3",
    "adept/fuyu-8b",
    "nvidia/llama-3.1-nemotron-51b-instruct",
    "databricks/dbrx-instruct",
    "zyphra/zamba2-7b-instruct",
    "nvidia/nemotron-4-340b-instruct",
    "google/codegemma-7b",
    "ibm/granite-3.0-8b-instruct",
    "nvidia/nemotron-4-340b-reward",
    "nvidia/riva-translate-4b-instruct",
    "nvidia/llama-nemotron-embed-vl-1b-v2",
    "mistralai/mistral-7b-instruct-v0.3",
    "nvidia/neva-22b",
    "nvidia/embed-qa-4",
    "writer/palmyra-fin-70b-32k",
    "nvidia/nemotron-3-embed-1b",
    "writer/palmyra-med-70b-32k",
    "aisingapore/sea-lion-7b-instruct",
    "microsoft/phi-3-vision-128k-instruct",
    "google/gemma-2b",
    "ibm/granite-3.0-3b-a800m-instruct",
    "nvidia/llama-3.2-nv-embedqa-1b-v1",
    "nvidia/nv-embedcode-7b-v1",
    "nvidia/vila",
    "meta/codellama-70b",
    "mistralai/codestral-22b-instruct-v0.1",
    "google/recurrentgemma-2b",
    "microsoft/kosmos-2",
    "nvidia/nv-embed-v1",
    "nvidia/llama-3.1-nemotron-70b-instruct",
    "nvidia/nv-embedqa-e5-v5",
    "writer/palmyra-med-70b",
    "meta/llama2-70b",
    "microsoft/phi-3.5-moe-instruct",
    "ibm/granite-8b-code-instruct",
    "nvidia/llama-nemotron-embed-1b-v2",
    "nvidia/cosmos-reason2-8b",
];

/// 判断模型是否已被上游弃用
/// 特殊专属上游临时暂停开关（admin_settings.special_model_suspended，后台 60s 刷新）

pub fn is_deprecated(id: &str) -> bool {
    // 官方自营上游模型（acu/）：走本机 DS2API 独立上游，不受 NIM 实时列表影响，默认始终可用
    if crate::constants::is_acu_model(id) {
        return false;
    }
    // 上游同步生效时：以 NIM /v1/models 实时列表为权威（不在列表 = 已下线弃用）
    // 同步未生效（启动早期/失败）：回退静态弃用列表，避免误删
    if crate::model::upstream::sync_active() {
        !crate::model::upstream::is_available_upstream(id)
    } else {
        DEPRECATED_MODELS.contains(&id)
    }
}

/// 弃用模型集合（含元数据，供管理后台/前端展示"已弃用"标签）
pub fn deprecated_models() -> Vec<&'static ModelInfo> {
    DEPRECATED_MODELS
        .iter()
        .filter_map(|id| NIMMODEL_CATALOG.get(*id))
        .collect()
}

/// 可用模型数（catalog 总数 - 弃用数）
pub fn available_model_count() -> usize {
    NIMMODEL_CATALOG.len() - DEPRECATED_MODELS.len()
}
